name: hhm_flutter
description: Privacy-preserving HHM resident and visitor applications for mobile, desktop, and web.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  ores_otel_flutter:
    git:
      url: https://github.com/ores-otel/ores-otel-flutter.git
      ref: c7cf306eee7b07408057753251f937ea58f8e9ed
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
